<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UserNameField</name>
   <tag></tag>
   <elementGuidId>000a2ab5-e1f4-4797-8641-98fe58b3caa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#i0116</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@type,'email')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
