<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_inputDataTextBox</name>
   <tag></tag>
   <elementGuidId>75ecfdd7-57ce-4725-9769-22457f12f0af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>((//div[@class='wtSpreader']//tr)[${param1}]//td[contains(@class,'ht')])[${param2}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
