<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_textInPopup</name>
   <tag></tag>
   <elementGuidId>53ec372c-96c3-4f4f-9caa-313ff75766db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2/following-sibling::div//h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
