<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_filter</name>
   <tag></tag>
   <elementGuidId>e824202b-9050-44d0-9e16-9fc0c6044e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//span[normalize-space(text())='${param}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
